version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: 'edtech-postgres'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - ai-service-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: 'redis/redis-stack:latest'
    container_name: 'edtech-redis'
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '${REDIS_PORT}:6379'
      - '8001:8001'
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru"
    networks:
      - ai-service-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: 'edtech-mongodb'
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - ai-service-network
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: 'edtech-mongo-ui'
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/?authSource=admin
    networks:
      - ai-service-network
    depends_on:
      mongodb:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    container_name: 'edtech-minio'
    restart: always
    ports:
      - '${MINIO_API_PORT}:9000'
      - '${MINIO_CONSOLE_PORT}:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

networks:
  ai-service-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  minio_data:

